# Experimental!
Input ← &rl(⋕°/$"_,_") &fo"input"

Part₁ ← (
  ⊸(↙1000⊏⍏⊸≡/(⩜⌵-) ⧅<2)         # Find shortest connections
  ∧(⊂□ /◇⊂ °˜□₂⊕□ ⊸≡⌞◇(/↥∊)) ⊙⍚¤ # Apply them
  /×↙¯3⍆ ≡◇⧻                     # Multiply sizes of largest circuits
)

Part₂ ← (
  ⊸(⊏⍏⊸≡/(⩜⌵-) ⧅<2)  # All connections, sorted
  ⤚(⊢⊚≡/↥=⊓(⊛₁|-1⧻)) # When is the last box connected?
  /×≡⊢⊏              # Multiply X coordinates
)

$Part₁ Part₁ Input
$Part₂ Part₂ Input
